### ISSUE TITLE
Error with jinja2 3.1.0, due to autoescape attribute

### ISSUE THREAD

**Issue by chokribr** [inveniosoftware/invenio-userprofiles#129]
## Describe the bug
I've got  the following error when runnig python setup.py extract_messages   AttributeError: module 'jinja2.ext' has no attribute 'autoescape' 
Seems that autoescape attribute had been deprecated

**Comment by lnielsen** [comment]
Are you running it on User Profiles? Can you copy/paste here the full command and full stracktrace that you see in the output.

**Comment by chokribr** [comment]
[root@pist3-dev invenio-userprofiles]# python setup.py extract_messages 
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
running extract_messages
extracting messages from invenio_userprofiles/__init__.py (encoding="utf-8")
extracting messages from invenio_userprofiles/admin.py (encoding="utf-8")
extracting messages from invenio_userprofiles/api.py (encoding="utf-8")
extracting messages from invenio_userprofiles/config.py (encoding="utf-8")
extracting messages from invenio_userprofiles/ext.py (encoding="utf-8")
extracting messages from invenio_userprofiles/forms.py (encoding="utf-8")
extracting messages from invenio_userprofiles/models.py (encoding="utf-8")
extracting messages from invenio_userprofiles/validators.py (encoding="utf-8")
extracting messages from invenio_userprofiles/version.py (encoding="utf-8")
extracting messages from invenio_userprofiles/views.py (encoding="utf-8")
extracting messages from invenio_userprofiles/alembic/71634726ec7e_create_userprofiles_branch.py (encoding="utf-8")
extracting messages from invenio_userprofiles/alembic/c25ef2c50ffa_create_userprofiles_tables.py (encoding="utf-8")
extracting messages from invenio_userprofiles/templates/invenio_userprofiles/base.html (encoding="utf-8", extensions="jinja2.ext.autoescape, jinja2.ext.with_")
Traceback (most recent call last):
  File "/usr/local/src/invenio-userprofiles/setup.py", line 77, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/src/invenio-userprofiles/.eggs/Babel-2.9.1-py3.9.egg/babel/messages/frontend.py", line 481, in run
    for filename, lineno, message, comments, context in extracted:
  File "/usr/local/src/invenio-userprofiles/.eggs/Babel-2.9.1-py3.9.egg/babel/messages/extract.py", line 149, in extract_from_dir
    for message_tuple in check_and_call_extract_file(
  File "/usr/local/src/invenio-userprofiles/.eggs/Babel-2.9.1-py3.9.egg/babel/messages/extract.py", line 207, in check_and_call_extract_file
    for message_tuple in extract_from_file(
  File "/usr/local/src/invenio-userprofiles/.eggs/Babel-2.9.1-py3.9.egg/babel/messages/extract.py", line 243, in extract_from_file
    return list(extract(method, fileobj, keywords, comment_tags,
  File "/usr/local/src/invenio-userprofiles/.eggs/Babel-2.9.1-py3.9.egg/babel/messages/extract.py", line 325, in extract
    for lineno, funcname, messages, comments in results:
  File "/usr/local/lib/python3.9/site-packages/jinja2/ext.py", line 808, in babel_extract
    extensions[import_string(extension_name)] = None
  File "/usr/local/lib/python3.9/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
