### ISSUE TITLE
migration: investigate alembic upgrade errors

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-userprofiles#141]
Users reported that the command `invenio alembic upgrade` produces errors when migrating from v8 to v9:

```
$ invenio alembic upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 17c703ce1eb7 -> 676dd587542d, Create funders vocabulary table.
INFO  [alembic.runtime.migration] Running upgrade 676dd587542d -> e1146238edd3, Create awards table.
INFO  [alembic.runtime.migration] Running upgrade e12419831262 -> 999dcbd19ace, Add versioning information to models.
INFO  [alembic.runtime.migration] Running upgrade 999dcbd19ace -> dfbdf43a3e96, Separate login info from user table.
INFO  [alembic.runtime.migration] Running upgrade dfbdf43a3e96 -> 62efc52773d4, Create UserIdentity table.
INFO  [alembic.runtime.migration] Running upgrade f701a32e6fbe -> fbe746957cfc, Create member tables
INFO  [alembic.runtime.migration] Running upgrade fbe746957cfc -> 5b478fe7ef7f, Create featured communities table
INFO  [alembic.runtime.migration] Running upgrade 5b478fe7ef7f -> a3f5a8635cbb, Remove version table
INFO  [alembic.runtime.migration] Running upgrade c25ef2c50ffa -> 41157f1933d6, Remove table.
Traceback (most recent call last):
  File "/home/linux/project/tug/v9.2/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/linux/project/tug/v9.2/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "username" of relation "accounts_user" does not exist
LINE 1: UPDATE accounts_user SET  username = 'idp-77aba62cdb768bf1',...
```

A second user provided its alembic `heads` and `current`:

```
# invenio alembic current
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
71634726ec7e (9848d0149abd) -> c25ef2c50ffa (invenio_userprofiles) (head), Create userprofiles tables.
862037093962 -> 07fb52561c5c (invenio_records) (head), Alter column from json to jsonb.
2da9a03b0833 (2e97565eba72, 862037093962) -> 1ba76da94103 (invenio_records_files, default) (head), Create records files tables.
88d1463de5c0 -> a3957490361d (invenio_rdm_records) (head), Remove PIDRelations tables.
f615cee99600 -> 999c62899c20 (invenio_pidstore) (head), Create pidstore tables.
97bbc733896c -> bff1f190b9bd (invenio_oauthclient, default) (head), Add Timestamp to oauthclient tables.
12a88921ada2 -> 4e57407b8e4a (default, invenio_oauth2server) (head), Add on delete cascade.
759d47cbdba7 -> e655021de0de (invenio_oaiserver) (head), Create oiaserver tables.
9848d0149abd -> e12419831262 (invenio_accounts) (head), Add new columns on SessionActivity.
dbe499bfda43 -> 04480be1593e (invenio_access) (head), Add ActionSystemRoles.
8ed1a438601c, 88d1463de5c0 (de9c14cbb0b2, a14fa442680f) -> 9e0ac518b9df (invenio_rdm_records) (head) (mergepoint), Create records/communities M2M table.
4a9a4fd235f8 -> 17c703ce1eb7 (invenio_vocabularies) (head), Create names table.
de9c14cbb0b2 (9848d0149abd) -> f261e5ee8743 (invenio_communities) (head), Create communities members table.
8ae99b034410 -> a29271fd78f8 (invenio_files_rest) (head), Create files object partial unique index.

```

```
# invenio alembic heads
dbdbc1b19cf2 -> 35c1075e6360 (default) (effective head), Force naming convention.
8ae99b034410 -> a29271fd78f8 (invenio_files_rest) (head), Create files object partial unique index.
862037093962 -> 07fb52561c5c (invenio_records) (head), Alter column from json to jsonb.
dbe499bfda43 -> 04480be1593e (invenio_access) (head), Add ActionSystemRoles.
9848d0149abd -> e12419831262 (invenio_accounts) (head), Add new columns on SessionActivity.
71634726ec7e (9848d0149abd) -> c25ef2c50ffa (invenio_userprofiles) (head), Create userprofiles tables.
4a9a4fd235f8 -> 17c703ce1eb7 (invenio_vocabularies) (head), Create names table.
f615cee99600 -> 999c62899c20 (invenio_pidstore) (head), Create pidstore tables.
12a88921ada2 -> 4e57407b8e4a (invenio_oauth2server, default) (head), Add on delete cascade.
8ed1a438601c, 88d1463de5c0 (de9c14cbb0b2, a14fa442680f) -> 9e0ac518b9df (invenio_rdm_records) (head) (mergepoint), Create records/communities M2M table.
88d1463de5c0 -> a3957490361d (invenio_rdm_records) (head), Remove PIDRelations tables.
2da9a03b0833 (2e97565eba72, 862037093962) -> 1ba76da94103 (invenio_records_files, default) (head), Create records files tables.
759d47cbdba7 -> e655021de0de (invenio_oaiserver) (head), Create oiaserver tables.
97bbc733896c -> bff1f190b9bd (default, invenio_oauthclient) (head), Add Timestamp to oauthclient tables.
de9c14cbb0b2 (9848d0149abd) -> f261e5ee8743 (invenio_communities) (head), Create communities members table.
5cd30a3503c9 -> a14fa442680f (invenio_requests) (effective head), Create tables.
```

**Comment by alejandromumo** [comment]
It seems that migration  `eb9743315a9d` was not executed, even though it down revision was. Additionally, user confirmed that the migration file existed.

We tested upgrading the whole `invenio_accounts` branch first and then proceed with upgrading the rest of the migrations. This fixed the issue for the user. 

This issue is not happening to everyone, therefore we decided to update the migration recipe with the "branch upgrade" command and the migration file itself to depend on the `invenio_account` migration (see attached PR)
