### ISSUE TITLE
Setting SECURITY_CHANGEABLE to False leads to internal error

### ISSUE THREAD

**Issue by omelkonian** [inveniosoftware/invenio-userprofiles#36]
To reproduce in the example app:

1. Add `SECURITY_CHANGEABLE=False` to `app.config.update()`
2. Run server and you will get this error 
```
Traceback (most recent call last):
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/src/invenio-userprofiles/invenio_userprofiles/views.py", line 98, in profile
    verification_form=verification_form,)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/src/invenio-userprofiles/invenio_userprofiles/templates/invenio_userprofiles/settings/profile.html", line 30, in top-level template code
    {% set panel_icon = "fa fa-user" %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/page_settings.html", line 25, in top-level template code
    {%- extends config.THEME_BASE_TEMPLATE %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/page.html", line 73, in top-level template code
    {%- block body %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/page.html", line 79, in block "body"
    {%- block body_inner %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/page.html", line 80, in block "body_inner"
    {%- block page_header %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/page.html", line 81, in block "page_header"
    {% include "invenio_theme/header.html" %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/header.html", line 25, in top-level template code
    {%- block navbar %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/header.html", line 45, in block "navbar"
    {%- block navbar_inner %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/header.html", line 75, in block "navbar_inner"
    {%- block navbar_right %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/header.html", line 76, in block "navbar_right"
    {%- include "invenio_theme/header_login.html" %}
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/invenio_theme/templates/invenio_theme/header_login.html", line 42, in top-level template code
    <li><a href="{{ item.url }}">{{ item.text|safe }}</a></li>
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask_menu/__init__.py", line 255, in url
    return url_for(self._endpoint, **args)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/home/orestis/.virtualenvs/invenio-userprofiles/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'security.change_password'. Did you mean 'security.reset_password' instead?

```

**Comment by omelkonian** [comment]
Maybe it is invenio-theme's issue, but I cannot reproduce the error there.

**Comment by lnielsen** [comment]
https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/views.py#L63-L90

**Comment by omelkonian** [comment]
So we should register them only when `CHANGEABLE=False`?
