### ISSUE TITLE
global: fix build errors

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-userprofiles#96]
https://travis-ci.org/inveniosoftware/invenio-userprofiles/jobs/656679868

Fix also deprecation warning in Travis config:
https://travis-ci.org/inveniosoftware/invenio-userprofiles/jobs/656679868/config

**Comment by diegodelemos** [comment]
After changing:
```diff
diff --git a/setup.py b/setup.py
index 3f1c0c5..16b33ef 100644
--- a/setup.py
+++ b/setup.py
@@ -31,7 +31,7 @@ tests_require = [
 
 extras_require = {
     'admin': [
-        'invenio-admin>=1.0.0',
+        'invenio-admin>=1.1.2',
     ],
     'docs': [
         'Sphinx>=1.4.2',
@@ -66,8 +66,8 @@ install_requires = [
     'Flask-Mail>=0.9.1',
     'Flask-Menu>=0.4.0',
     'Flask-WTF>=0.13.1',
-    'Flask>=0.11.1',
-    'invenio-accounts>=1.0.0',
+    'Flask>=1.0.4',
+    'invenio-accounts>=1.1.3',
     'Werkzeug>=0.14.1',
     'WTForms>=2.0.1',
 ]
```

I am seeing:

```console
...
During handling of the above exception, another exception occurred:                                                                                                                                                 
Traceback (most recent call last):                                                                        
  File "/Users/rodrigdi/.virtualenvs/i-userprofiles/lib/python3.6/site-packages/_pytest/config/__init__.py", line 418, in _importconftest                                                                           
    mod = conftestpath.pyimport()
  File "/Users/rodrigdi/.virtualenvs/i-userprofiles/lib/python3.6/site-packages/py/_path/local.py", line 701, in pyimport                                                                                           
    __import__(modname)                                                                                                                                                                                             
  File "/Users/rodrigdi/.virtualenvs/i-userprofiles/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 296, in load_module                                                                             
    six.exec_(co, mod.__dict__)                                                                           
  File "/Users/rodrigdi/code/inveniosoftware/invenio-userprofiles/tests/conftest.py", line 19, in <module>                                                                                                          
    from flask_babelex import Babel                                                                       
  File "/Users/rodrigdi/.virtualenvs/i-userprofiles/lib/python3.6/site-packages/flask_babelex/__init__.py", line 23, in <module>                                                                                    
    from werkzeug import ImmutableDict                                                                                                                                                                              
ImportError: cannot import name 'ImmutableDict'
ERROR: could not load /Users/rodrigdi/code/inveniosoftware/invenio-userprofiles/tests/conftest.py
...
```
